### ISSUE TITLE
frequent Sync request timed out documentHighlights

### ISSUE THREAD

**Issue by johnbendi** [ananthakumaran/tide#113]
I keep getting this error message so frequently. What could be the cause?

Here is a copy of the backtrace that appears when it happens: 
```
Debugger entered--Lisp error: (error "Sync request timed out documentHighlights")
  signal(error ("Sync request timed out documentHighlights"))
  error("Sync request timed out %s" "documentHighlights")
  tide-send-command-sync("documentHighlights" (:file "~/projects/app/src/App.ts" :line 1 :offset 1 :filesToSearch ("~/projects/app/src/App.ts")))
  tide-command:documentHighlights()
  tide--hl-identifier()
  tide-hl-identifier()
  tide--hl-identifiers-function()
  apply(tide--hl-identifiers-function nil)
  timer-event-handler([t 0 0 100000 t tide--hl-identifiers-function nil idle 0])
```

**Comment by ananthakumaran** [comment]
Should be fixed in master. please re-open if you encounter any problems.

**Comment by johnbendi** [comment]
@ananthakumaran After updating the issue was resolved but another similar issue is still being triggered:
```
Debugger entered--Lisp error: (error "Sync request timed out quickinfo-full")
  signal(error ("Sync request timed out quickinfo-full"))
  error("Sync request timed out %s" "quickinfo-full")
  tide-send-command-sync("quickinfo-full" (:file "~/projects/app/src/app/q_a/services/answer.ts" :line 64 :offset 33))
  tide-command:quickinfo-full()
  tide-command:quickinfo()
  tide-eldoc-function()
  eldoc-print-current-symbol-info()
  #[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2]()
  apply(#[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil)
  timer-event-handler([t 0 0 500000 nil #[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil idle 0])

```
maybe this one needs to be made async too?

**Comment by ananthakumaran** [comment]
not sure. can you check how much times the server takes to respond? Look at the debugging section in readme for how to enable log. The default timeout (2 seconds) is quite high. Most of the time `tsserver` responds within few milli seconds.

**Comment by johnbendi** [comment]
@ananthakumaran I have enabled logging but I still can't make sense of why `quickinfo` keeps timing out. Please advice further on what to do. This timing out issue is getting on my nerves. The other one doesn't happen again so that's why I believe there's something you did to the other issue that needs to be done to this one.

**Comment by johnbendi** [comment]
Looking further at the source I see that `documentHighlights` uses `tide-send-command` while `quickinfo` uses `tide-send-command-sync`, could this be the problem?

**Comment by ananthakumaran** [comment]
Can you post the log file? Yes, quickinfo uses sync call, but tsserver should return within 2 seconds in most cases.

**Comment by johnbendi** [comment]
@ananthakumaran here is a sample:
```
Open files: 
~/projects/app1/src/app/user/user.service.ts
~/projects/app1/src/app/user/user.service.ts
~/projects/app1/src/app/user/user.service.ts
Info 28   event: {"seq":0,"type":"event","event":"configFileDiag","body":{"triggerFile":"~/projects/app1/src/app/user/user.service.ts","configFile":"~/projects/app1/tsconfig.json","diagnostics":[]}}
Perf 29   5::open: async elapsed time (in milliseconds) 1660.5745
Info 30   request: {"command":"configure","seq":"6","arguments":{"hostInfo":"GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.18.9)\n of 2017-02-04","file":"~/projects/app1/src/app/user/user.service.ts","formatOptions":{"tabSize":2,"indentSize":4,"insertSpaceAfterFunctionKeywordForAnonymousFunctions":true,"placeOpenBraceOnNewLineForFunctions":null}}}
Info 31   Host configuration update for file ~/projects/app1/src/app/user/user.service.ts
Info 32   response: {"seq":0,"type":"response","command":"configure","request_seq":"6","success":true}
Perf 33   6::configure: async elapsed time (in milliseconds) 0.5063
Info 34   request: {"command":"syntacticDiagnosticsSync","seq":"7","arguments":{"file":"~/projects/app1/src/app/user/user.service.ts"}}
Perf 35   7::syntacticDiagnosticsSync: elapsed time (in milliseconds) 3.2392
Info 36   response: {"seq":0,"type":"response","command":"syntacticDiagnosticsSync","request_seq":"7","success":true,"body":[]}
Info 37   request: {"command":"semanticDiagnosticsSync","seq":"8","arguments":{"file":"~/projects/app1/src/app/user/user.service.ts"}}
Perf 38   8::semanticDiagnosticsSync: elapsed time (in milliseconds) 188.7865
Info 39   response: {"seq":0,"type":"response","command":"semanticDiagnosticsSync","request_seq":"8","success":true,"body":[{"start":{"line":63,"offset":33},"end":{"line":63,"offset":54},"text":"Cannot find name 'CheckUserExistsAction'.","code":2304}]}
Info 40   request: {"command":"navbar","seq":"9","arguments":{"file":"~/projects/app1/src/app/user/user.service.ts"}}
Perf 41   9::navbar: elapsed time (in milliseconds) 40.0504
Info 42   response: {"seq":0,"type":"response","command":"navbar","request_seq":"9","success":true,"body":[{"text":"\"user.service\"","kind":"module","kindModifiers":"","spans":[{"start":{"line":1,"offset":1},"end":{"line":111,"offset":3}}],"childItems":[{"text":"Actions","kind":"alias","kindModifiers":"","spans":[{"start":{"line":7,"offset":18},"end":{"line":7,"offset":25}}],"childItems":[],"indent":0},{"text":"API_BASE_URL","kind":"alias","kindModifiers":"","spans":[{"start":{"line":10,"offset":10},"end":{"line":10,"offset":22}}],"childItems":[],"indent":0},{"text":"AppState","kind":"alias","kindModifiers":"","spans":[{"start":{"line":9,"offset":10},"end":{"line":9,"offset":18}}],"childItems":[],"indent":0},{"text":"Auth0Service","kind":"alias","kindModifiers":"","spans":[{"start":{"line":12,"offset":10},"end":{"line":12,"offset":22}}],"childItems":[],"indent":0},{"text":"AuthHttp","kind":"alias","kindModifiers":"","spans":[{"start":{"line":3,"offset":10},"end":{"line":3,"offset":18}}],"childItems":[],"indent":0},{"text":"Effect","kind":"alias","kindModifiers":"","spans":[{"start":{"line":7,"offset":10},"end":{"line":7,"offset":16}}],"childItems":[],"indent":0},{"text":"getIsUserLoggedIn","kind":"function","kindModifiers":"","spans":[{"start":{"line":18,"offset":5},"end":{"line":18,"offset":56}}],"childItems":[],"indent":0},{"text":"getUserProfile","kind":"function","kindModifiers":"","spans":[{"start":{"line":20,"offset":5},"end":{"line":20,"offset":50}}],"childItems":[],"indent":0},{"text":"getUserState","kind":"function","kindModifiers":"","spans":[{"start":{"line":16,"offset":29},"end":{"line":16,"offset":60}}],"childItems":[],"indent":0},{"text":"Http","kind":"alias","kindModifiers":"","spans":[{"start":{"line":2,"offset":10},"end":{"line":2,"offset":14}}],"childItems":[],"indent":0},{"text":"Injectable","kind":"alias","kindModifiers":"","spans":[{"start":{"line":1,"offset":10},"end":{"line":1,"offset":20}}],"childItems":[],"indent":0},{"text":"Observable","kind":"alias","kindModifiers":"","spans":[{"start":{"line":4,"offset":10},"end":{"line":4,"offset":20}}],"childItems":[],"indent":0},{"text":"RequestBase","kind":"alias","kindModifiers":"","spans":[{"start":{"line":11,"offset":10},"end":{"line":11,"offset":21}}],"childItems":[],"indent":0},{"text":"Store","kind":"alias","kindModifiers":"","spans":[{"start":{"line":6,"offset":10},"end":{"line":6,"offset":15}}],"childItems":[],"indent":0},{"text":"Subject","kind":"alias","kindModifiers":"","spans":[{"start":{"line":5,"offset":10},"end":{"line":5,"offset":17}}],"childItems":[],"indent":0},{"text":"UserService","kind":"class","kindModifiers":"export","spans":[{"start":{"line":22,"offset":1},"end":{"line":111,"offset":2}}],"childItems":[],"indent":0}],"indent":0},{"text":"getIsUserLoggedIn","kind":"function","kindModifiers":"","spans":[{"start":{"line":18,"offset":5},"end":{"line":18,"offset":56}}],"childItems":[],"indent":1},{"text":"getUserProfile","kind":"function","kindModifiers":"","spans":[{"start":{"line":20,"offset":5},"end":{"line":20,"offset":50}}],"childItems":[],"indent":1},{"text":"getUserState","kind":"function","kindModifiers":"","spans":[{"start":{"line":16,"offset":29},"end":{"line":16,"offset":60}}],"childItems":[],"indent":1},{"text":"UserService","kind":"class","kindModifiers":"export","spans":[{"start":{"line":22,"offset":1},"end":{"line":111,"offset":2}}],"childItems":[{"text":"constructor","kind":"constructor","kindModifiers":"","spans":[{"start":{"line":28,"offset":5},"end":{"line":60,"offset":6}}],"childItems":[],"indent":0},{"text":"_userInfo","kind":"property","kindModifiers":"","spans":[{"start":{"line":25,"offset":5},"end":{"line":25,"offset":20}}],"childItems":[],"indent":0},{"text":"_userInfo$","kind":"property","kindModifiers":"","spans":[{"start":{"line":26,"offset":5},"end":{"line":26,"offset":32}}],"childItems":[],"indent":0},{"text":"actions$","kind":"property","kindModifiers":"private","spans":[{"start":{"line":30,"offset":9},"end":{"line":30,"offset":34}}],"childItems":[],"indent":0},{"text":"authHttp","kind":"property","kindModifiers":"private","spans":[{"start":{"line":33,"offset":9},"end":{"line":33,"offset":35}}],"childItems":[],"indent":0},{"text":"authService","kind":"property","kindModifiers":"private","spans":[{"start":{"line":34,"offset":9},"end":{"line":34,"offset":42}}],"childItems":[],"indent":0},{"text":"checkUserRegistration","kind":"method","kindModifiers":"private","spans":[{"start":{"line":62,"offset":5},"end":{"line":64,"offset":6}}],"childItems":[],"indent":0},{"text":"getUserName","kind":"method","kindModifiers":"public","spans":[{"start":{"line":71,"offset":5},"end":{"line":80,"offset":6}}],"childItems":[],"indent":0},{"text":"getUserProfile","kind":"method","kindModifiers":"public","spans":[{"start":{"line":82,"offset":5},"end":{"line":84,"offset":6}}],"childItems":[],"indent":0},{"text":"http","kind":"property","kindModifiers":"private","spans":[{"start":{"line":32,"offset":9},"end":{"line":32,"offset":27}}],"childItems":[],"indent":0},{"text":"isUserAdmin","kind":"method","kindModifiers":"public","spans":[{"start":{"line":90,"offset":5},"end":{"line":94,"offset":6}}],"childItems":[],"indent":0},{"text":"isUserAuthenticated","kind":"method","kindModifiers":"public","spans":[{"start":{"line":86,"offset":5},"end":{"line":88,"offset":6}}],"childItems":[],"indent":0},{"text":"login","kind":"method","kindModifiers":"","spans":[{"start":{"line":102,"offset":5},"end":{"line":105,"offset":6}}],"childItems":[],"indent":0},{"text":"logout","kind":"method","kindModifiers":"","spans":[{"start":{"line":107,"offset":5},"end":{"line":110,"offset":6}}],"childItems":[],"indent":0},{"text":"reqBase","kind":"property","kindModifiers":"private","spans":[{"start":{"line":31,"offset":9},"end":{"line":31,"offset":37}}],"childItems":[],"indent":0},{"text":"store","kind":"property","kindModifiers":"private","spans":[{"start":{"line":29,"offset":9},"end":{"line":29,"offset":39}}],"childItems":[],"indent":0},{"text":"userInfo$","kind":"getter","kindModifiers":"","spans":[{"start":{"line":66,"offset":5},"end":{"line":69,"offset":6}}],"childItems":[],"indent":0}],"indent":1},{"text":"constructor","kind":"constructor","kindModifiers":"","spans":[{"start":{"line":28,"offset":5},"end":{"line":60,"offset":6}}],"childItems":[{"text":"<function>","kind":"function","kindModifiers":"","spans":[{"start":{"line":41,"offset":51},"end":{"line":58,"offset":10}}],"childItems":[],"indent":0}],"indent":2},{"text":"<function>","kind":"function","kindModifiers":"","spans":[{"start":{"line":41,"offset":51},"end":{"line":58,"offset":10}}],"childItems":[{"text":"<function>","kind":"function","kindModifiers":"","spans":[{"start":{"line":45,"offset":17},"end":{"line":56,"offset":18}}],"childItems":[],"indent":0}],"indent":3},{"text":"getUserName","kind":"method","kindModifiers":"public","spans":[{"start":{"line":71,"offset":5},"end":{"line":80,"offset":6}}],"childItems":[{"text":"_userInfo","kind":"let","kindModifiers":"","spans":[{"start":{"line":73,"offset":17},"end":{"line":73,"offset":26}}],"childItems":[],"indent":0},{"text":"<function>","kind":"function","kindModifiers":"","spans":[{"start":{"line":74,"offset":39},"end":{"line":76,"offset":14}}],"childItems":[],"indent":0}],"indent":2},{"text":"<function>","kind":"function","kindModifiers":"","spans":[{"start":{"line":74,"offset":39},"end":{"line":76,"offset":14}}],"childItems":[],"indent":3}]}
Info 43   request: {"command":"documentHighlights","seq":"10","arguments":{"file":"~/projects/app1/src/app/user/user.service.ts","line":1,"offset":1,"filesToSearch":["~/projects/app1/src/app/user/user.service.ts"]}}
Perf 44   10::documentHighlights: elapsed time (in milliseconds) 11.0636
Info 45   response: {"seq":0,"type":"response","command":"documentHighlights","request_seq":"10","success":false,"message":"No content available."}
Info 46   request: {"command":"quickinfo-full","seq":"11","arguments":{"file":"~/projects/app1/src/app/user/user.service.ts","line":16,"offset":1}}
Perf 47   11::quickinfo-full: elapsed time (in milliseconds) 2.5129
Info 48   response: {"seq":0,"type":"response","command":"quickinfo-full","request_seq":"11","success":false,"message":"No content available."}
Info 49   request: {"command":"documentHighlights","seq":"12","arguments":{"file":"~/projects/app1/src/app/user/user.service.ts","line":16,"offset":1,"filesToSearch":["~/projects/app1/src/app/user/user.service.ts"]}}
Perf 50   12::documentHighlights: elapsed time (in milliseconds) 4.7677
Info 51   response: {"seq":0,"type":"response","command":"documentHighlights","request_seq":"12","success":true,"body":[{"file":"~/projects/app1/src/app/user/user.service.ts","highlightSpans":[{"start":{"line":16,"offset":1},"end":{"line":16,"offset":7},"kind":"none"},{"start":{"line":17,"offset":1},"end":{"line":17,"offset":7},"kind":"none"},{"start":{"line":19,"offset":1},"end":{"line":19,"offset":7},"kind":"none"},{"start":{"line":23,"offset":1},"end":{"line":23,"offset":7},"kind":"none"}]}]}
Info 52   request: {"command":"documentHighlights","seq":"13","arguments":{"file":"~/projects/app1/src/app/user/user.service.ts","line":16,"offset":1,"filesToSearch":["~/projects/app1/src/app/user/user.service.ts"]}}
Perf 53   13::documentHighlights: elapsed time (in milliseconds) 0.8995
Info 54   response: {"seq":0,"type":"response","command":"documentHighlights","request_seq":"13","success":true,"body":[{"file":"~/projects/app1/src/app/user/user.service.ts","highlightSpans":[{"start":{"line":16,"offset":1},"end":{"line":16,"offset":7},"kind":"none"},{"start":{"line":17,"offset":1},"end":{"line":17,"offset":7},"kind":"none"},{"start":{"line":19,"offset":1},"end":{"line":19,"offset":7},"kind":"none"},{"start":{"line":23,"offset":1},"end":{"line":23,"offset":7},"kind":"none"}]}]}
Info 55   request: {"command":"quickinfo-full","seq":"14","arguments":{"file":"~/projects/app1/src/app/user/user.service.ts","line":16,"offset":1}}
Perf 56   14::quickinfo-full: elapsed time (in milliseconds) 0.5127
Info 57   response: {"seq":0,"type":"response","command":"quickinfo-full","request_seq":"14","success":false,"message":"No content available."}
Info 58   request: {"command":"documentHighlights","seq":"15","arguments":{"file":"~/projects/app1/src/app/user/user.service.ts","line":16,"offset":1,"filesToSearch":["~/projects/app1/src/app/user/user.service.ts"]}}
```

**Comment by johnbendi** [comment]
@ananthakumaran did you get anything useful from the logs?

**Comment by ananthakumaran** [comment]
I haven't made any progress. According to the logs, the latency is about ~3ms. Not sure why you get that error.

**Comment by johnbendi** [comment]
@ananthakumaran I'm really frustrated about this persistent error and it's giving me a nasty user experience. One thing I also observe is the emacs UI freezes shortly before the error. That is when I press the up or down arrow key before the command returns which is most likely as a result of the synchronous call.

**Comment by ananthakumaran** [comment]
can you provide your emacs version and os info

**Comment by johnbendi** [comment]
`GNU Emacs 25.1.1 (x86_64-ubuntu-linux-gnu, GTK+ Version 3.18.9) of 2017-02-04`

Thanks for reopening this issue.
