### ISSUE TITLE
Tide ignores tsconfig.json settings

### ISSUE THREAD

**Issue by jclangst** [ananthakumaran/tide#312]
When submitting issues to this project, please include the following information.

## Checklist

- [x] I have searched both open and closed issues and cannot find a duplicate.
- [X] I can [reproduce the problem](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#use-the-latest-version-of-the-relevant-packages) with the latest version of the relevant packages.
- [x] The problem still occurs after I issued [`M-x tide-restart-server`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#try-m-x-tide-restart-server) in the buffer where I had the problem.
- [X] I verified that the version and the configuration file path reported by [`M-x tide-verify-setup`](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#check-the-information-reported-by-m-x-tide-verify-setup) are correct.
- [X] If [tide *is reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should not be reported*, I can run `tsc` (and `tslint`, if applicable) without the error or warning I'm seeing in tide.
- [x] If [tide is *not reporting*](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#the-behavior-of-cli-tools-agrees-with-your-expectations) an error or warning I think *should be reported*, `tsc` (or `tslint`, if applicable) reports the error or warning I was expecting to see.
- [ ] I am [positive](https://github.com/ananthakumaran/tide/wiki/Explanations-about-the-Issue-Reporting-Checklist#how-to-determine-which-project-the-problem-belongs-to) the problem does not belong to `typescript-mode` or `tsserver`.

## Relevant Version Numbers

- Tide: 20190321.1611
- TypeScript: 3.4.5 (also tried on 3.3)
- Emacs: 26.2

(The list above is minimal. Make sure to include any other version numbers relevant to your report.)

## Steps to Reproduce the Bug

(1) Set up typescript project
(2) Define function with implicit any behavior like such:

```typescript
function (id) {
  return id;
}
```
(3) Set up tsconfig to allow implicit any's via `"noImplicitAny": false` (which is also the default, so really no need to do this unless you want to be double sure). Here is my current setup:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "lib": ["es6", "dom"],
        "sourceMap": true,
        "declaration": true,
        "moduleResolution": "node",
        "rootDir": "src",
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noImplicitAny": false,
        "strictNullChecks": true,
        "allowJs": false,
        "esModuleInterop": true,
        "noUnusedParameters": true,
        "noUnusedLocals": true,
        "skipLibCheck": true,
        "strictPropertyInitialization": true,
        "strictBindCallApply": true,
        "resolveJsonModule": true,
        "outDir": "lib",
        "declarationDir": "lib/types"
    },
    "exclude": [
        "node_modules"
    ],
    "include": [
        "src"
    ]
}
```

(4) Run `tide-project-errors` within emacs with the file with the function from (2) in the current buffer

(5) Run `tsc -p tsconfig.json` from the command line

## Expected Behavior

The same errors should be reported.

## Actual Behavior

Tide reports implicit any errors while `tsc` follows the settings of `tsconfig.json`.

# Additional Notes

(1) It appears that Tide ignores my project's `tsconfig.json` when computing errors because the discrepency happens for multiple keys not just `allowImplicitAny`. I have checked that `tide-verify-setup` points to the right config file.

(2) I have tried using multiple versions of the `typescript` package from `npm` in my project; same issues every time. I verified that Tide was picking up the new versions.

(3) Not sure if this is an issue with Tide or `tsserver`; however, since `tsc` was performing as expected, my assumption is that Tide is likely the culprit. I didn't see any issues filed with `tsserver`.

**Comment by lddubeau** [comment]
Thank you for providing steps to reproduce the issue, but just with these steps I'm not able to reproduce the problem here. I would suggest putting out a repository that contains a minimal reproduction case that we can clone.

**Comment by jclangst** [comment]
Thank you for the quick response.

Here is a demo repository:
https://github.com/jclangst/tide-tss-err-bug

When I reproduced my steps using this demo repo, I still get the error but in this fresh project it is labeled as a "suggestion error". 

Here is a screenshot comparing the output of running `tide-project-errors` in my two projects:

![tide-error](https://user-images.githubusercontent.com/13301098/57183295-44224580-6e70-11e9-8ec6-c5d34749f203.png)

The left one is from the original repo from which I raised this bug; note that there is no summary stats at the bottom. The right one is the result of this clean repo.

Does this help?

**Comment by jclangst** [comment]
I also just want to note that between the two projects from above, all of the config is the same (same emacs, same `init.el` file, same `tsconfig.json`, etc. The only difference is that there is not a linter in the demo repo.

**Comment by jclangst** [comment]
I am relatively new to emacs but here is my `init.el` in case it helps:

```elisp
(desktop-save-mode 1)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Keybindings
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(global-set-key (kbd "C-d") 'forward-char)
(global-set-key (kbd "C-a") 'backward-char)
(global-set-key (kbd "C-w") 'previous-line)
(global-set-key (kbd "C-s") 'next-line)
(global-set-key (kbd "C-S-s") 'next-line)
(global-set-key (kbd "C-S-w") 'previous-line)
(global-set-key (kbd "C-S-a") 'backward-word)
(global-set-key (kbd "C-S-d") 'forward-word)
(global-set-key (kbd "M-d") 'sp-forward-sexp)
(global-set-key (kbd "M-a") 'sp-backward-sexp)
(global-set-key (kbd "M-s") 'sp-down-sexp)
(global-set-key (kbd "M-w") 'sp-up-sexp)

(cua-mode t)
(setq cua-auto-tabify-rectangles nil) ;; Don't tabify after rectangle commands
(transient-mark-mode 1) ;; No region when it is not highlighted
(setq cua-keep-region-after-copy t) ;; Standard Windows behaviour(global-set-key (kbd "C-x") ctl-x-map)

;; Searching shortcuts
(global-set-key (kbd "C-f") 'helm-occur)
(global-set-key (kbd "C-S-f") 'helm-projectile-ag)

;; Shortcuts for opening and reloading the config file
(global-set-key (kbd "<f5>") (lambda() (interactive)(find-file "~/.emacs.d/init.el")))
(global-set-key (kbd "<f6>") (lambda() (interactive)(load-file "~/.emacs.d/init.el")))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Set Up MELPA as the package repo
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (when no-ssl
    (warn "\
Your version of Emacs does not support SSL connections,
which is unsafe because it allows man-in-the-middle attacks.
There are two things you can do about this warning:
1. Install an Emacs version that does support SSL and be safe.
2. Remove this warning from your init file so you won't see it again."))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives (cons "gnu" (concat proto "://elpa.gnu.org/packages/")))))
(package-initialize)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(helm-mode t)
 '(package-selected-packages
   (quote
    (helm-ag rg helm-rg smartparens helm-swoop ace-jump-mode dired-filter dired-rainbow dired-avfs dired-open dash dired-subtree npm-mode diff-hl web-mode tide magit js2-mode helm-projectile helm ace-window zenburn-theme add-node-modules-path ## flycheck lsp-ui company-lsp lsp-mode projectile))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Set up the themes
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(load-theme 'zenburn t)
(setq global-linum-mode t)
(global-linum-mode t)
(set-face-attribute 'fringe nil :background "#3F3F3F" :foreground "#3F3F3F")
(smartparens-global-mode 1)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Set up helm
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(require 'helm-config)
(global-set-key (kbd "M-x") #'helm-M-x)
(global-set-key (kbd "C-x r b") #'helm-filtered-bookmarks)
(global-set-key (kbd "C-x C-f") #'helm-find-files)
(define-key helm-map (kbd "C-s") 'helm-next-line)
(define-key helm-map (kbd "C-w") 'helm-previous-line)
(helm-mode 1)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Set up ace-window
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(global-set-key (kbd "M-o") 'ace-window)
(setq-default header-line-format mode-line-format)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Set Up Projectile for managing projects
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(projectile-mode +1)
(define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
(setq projectile-enable-caching t)
(setq projectile-indexing-method 'native)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Sets Up Language Servers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(require 'lsp-mode)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Sets up code completion
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(require 'company-lsp)
(push 'company-lsp company-backends)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Sets up lsp ui
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(require 'lsp-ui)
(add-hook 'lsp-mode-hook 'lsp-ui-mode)
(add-hook 'lsp-ui-mode-hook 'flycheck-mode)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Javascript Config
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun my/use-eslint-from-node-modules ()
  (let* ((root (locate-dominating-file
                (or (buffer-file-name) default-directory)
                "node_modules"))
         (eslint
          (and root
               (expand-file-name "node_modules/.bin/eslint"
                                 root))))
    (when (and eslint (file-executable-p eslint))
      (setq-local flycheck-javascript-eslint-executable eslint))))

(add-hook 'flycheck-mode-hook #'my/use-eslint-from-node-modules)
(add-hook 'js2-mode-hook #'lsp)
(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
(add-to-list 'auto-mode-alist '("\\.jsx?\\'" . js2-jsx-mode))
(add-to-list 'interpreter-mode-alist '("node" . js2-mode))
(add-to-list 'interpreter-mode-alist '("node" . js2-jsx-mode))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Typescript Config
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun setup-tide-mode ()
  (interactive)
  (tide-setup)
  (flycheck-mode +1)
  (setq flycheck-check-syntax-automatically '(idle-change save new-linen mode-enabled))
  (setq flycheck-idle-change-delay 0.2)
  (eldoc-mode +1)
  (tide-hl-identifier-mode +1)
  (auto-save-visited-mode +1)
  (setq auto-save-visited-interval 1)
  (setq tide-tsserver-process-environment '("TSS_LOG=-level verbose -file /tmp/tss.log"))
  ;; company is an optional dependency. You have to
  ;; install it separately via package-install
  ;; `M-x package-install [ret] company`
  (company-mode +1))

;; aligns annotation to the right hand side
(setq company-tooltip-align-annotations t)

;; formats the buffer before saving
(add-hook 'before-save-hook 'tide-format-before-save)

(add-hook 'typescript-mode-hook #'setup-tide-mode)

(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . web-mode))
(add-hook 'web-mode-hook
          (lambda ()
            (when (string-equal "tsx" (file-name-extension buffer-file-name))
              (setup-tide-mode))))
;; enable typescript-tslint checker
(flycheck-add-mode 'typescript-tslint 'web-mode)

(eval-after-load "tide"
  '(define-key tide-mode-map (kbd "C-q") 'tide-jump-to-definition))
(eval-after-load "tide"
  '(define-key tide-mode-map (kbd "C-e") 'tide-references))
(add-hook 'tide-references-mode-hook
	  (lambda ()
	    (local-set-key (kbd "C-s") 'tide-find-next-reference)
	    (local-set-key (kbd "C-w") 'tide-find-previous-reference)
	    ))
```

**Comment by lddubeau** [comment]
I've cloned the repository. I'm still not seeing an error in the way tide behave. If I tweak ``noImplicitAny`` in the reproduction case, both `tsc` and `tide` behave as expected:

1. If ``noImplicitAny`` is turned on, `tsc` reports an error, `tide-project-errors` reports an error, and when I load `index.ts`, there's a red line under the `input` parameter of `testFunction`, reporting an error.

2. If ``noImplicitAny`` is turned off `tsc` reports nothing, `tide-project-errors` reports a suggestion, and when I load `index.ts`, there's a green line under under the `input` parameter of `testFunction`, reporting a suggestion.

@jclangst In your screenshot, I assume the first diagnostic message in the buffer on the left is the one that you find problematic. Are you sure that it is an *error* and not just a *suggestion*? If I use your repository and modify `index.ts` to load a module for which there is no TypeScript declaration, I get a *suggestion* of the same form as the first message in your screenshot. When `noImplicitAny` is turned on, then it becomes an error but the text of the message is exactly the same.

**Comment by jclangst** [comment]
Thank you for follow up.

I think I see what is happening with the error vs. suggestion distinction. A couple of follow-up questions:

(1) For my original project, I am not getting any summary statistics that would have helped me differentiate. I am _not_ sure whether it is a suggestion or error. How do I tell? Is the lack of summary stats a bug?
(2) The suggestions seem to be examining my `node_modules` folder even though I explicitly exclude it in `tsconfig.json`. Is this a bug or are the suggestions configurable somewhere else?
(3) Is there a way to get that error page without the suggestions so that it only shows the actual compiler errors?

**Comment by lddubeau** [comment]
> (1) For my original project, I am not getting any summary statistics that would have helped me differentiate. I am _not_ sure whether it is a suggestion or error. How do I tell? Is the lack of summary stats a bug?

Oops... I meant to address the lack of summary in my previous comment but forgot. I don't know why you're not getting a summary. The lack of summary may actually be a bug in `tide-project-errors`.

However, I don't think the summary is *necessary* for our immediate purpose here. `tide-project-errors` allows navigating to the messages that it shows. Run `tide-project-errors`, go to the line that contains the message you are interested about. Hit the ENTER key. That should take you to the exact location where the message originated. If there's a green underline under whichever syntax token caused the message, then it is a suggestion. If it is red, it is an error.

> (2) The suggestions seem to be examining my `node_modules` folder even though I explicitly exclude it in `tsconfig.json`. Is this a bug or are the suggestions configurable somewhere else?

Whatever is excluded by `tsconfig.json` should not cause suggestions.

> (3) Is there a way to get that error page without the suggestions so that it only shows the actual compiler errors?

Not that I know of, but, although I use tide daily, I don't use `tide-project-errors` very often.

**Comment by jclangst** [comment]
I added the below to my `init.el`:

```elisp
(setq tide-user-preferences '(:disableSuggestions t))
```

This had the weird effect of not showing anything when there are no compiler errors for the demo project linked above (including no summary stats line); when there are compiler errors, they are shown.

 For the original project, the output doesn't change (suggestions included).

Based on this I am wondering if Tide caches any information about my projects anywhere which might explain the differences between my two projects. I have deleted and reinstalled the `tsserver` (and all of the `node_modules`) several times but that doesnt seem to fix the issue.

**Comment by jclangst** [comment]
To respond to your comment:

(1) I think it must be a bug. If there is no way to turn off suggestions on this buffer in Tide, it'd be ideal if there way some sorting options or highlighting that could differentiate the types of errors (as I don't really see suggestions as errors -- that's why I have my linter).

(2) It seems to be inspecting the definition files only in `node_modules/@types` for whatever reason. I think this is an issue with tsserver and not Tide, however.

(3) I think I answered my question with the above change to `init.el`.

As a follow-up, you mentioned you don't use this often. Do you use an alternative utility to explore the errors in your projects?

**Comment by jclangst** [comment]
As a side note, it appears that disabling suggestions only affects that `tide-project-errors` output and does not disable the underlining.

**Comment by jclangst** [comment]
As another test, I went ahead and did a fresh clone of the original repo at a different location on my file system and restarted emacs entirely. Here is the current behavior:

(1) Tide is now respecting the tsconfig settings for true compiler errors only;
(2) After disabling the suggestions as above, I was still getting the suggestion errors UNTIL I open each file with suggestion errors in a buffer. After that point, the suggestion errors no longer appear.
(3) This remains UNTIL I restart `tsserver`.

So, I am wondering if that is either a bug with `tsserver` or Tide needs to be passing some data to `tsserver` that it isn't initially but then does whenever a file buffer is opened.

**Comment by gdanov** [comment]
I had exactly the same behavior as @jclangst but with javascirpt project, having jsconfig.json in the root folder.

After copying jsconfig.json to tsconfig.json, both flycheck and  tide stopped nagging me with the "implicit any" errror. 

I suspect this may be tsserver, not tide issue.

tide version: 20190321.1611
typescript version: "3.4.5"

**Comment by jclangst** [comment]
@gdanov To clarify on the behavior you're seeing, are you saying that for a javascript project you get implicit any errors without having a tsconfig.json?

I ask because I think your issue might be slightly separate. Here is how I would re-summarize my issue knowing what I know now:

(1) Tide does not report summary statistics for `tide-project-errors` in some cases. I've noticed that this happens when (a) I have no project errors and (b) I have `:disableSuggestions t`. I think this is likely a bug with Tide.

(2) In the Tide error summary buffer, there is no way to differentiate the type of errors (e.g., syntax errors vs mere suggestions) without actually opening the files with the errors/suggestions and keeping track manually. When coupled with (1), this led to my initial confusion. This functionality is more of a feature request.

(3) The `:disableSuggestions t` option seems to only affect the `tide-project-errors` output and not flycheck as a I still get underlining in the code files. I prefer this behavior actually, but it seems a bit unintuitive as it seems that `:disableSuggestions` is passed directly to `tsserver` so I wouldn't expect any suggestions (outside of my linter) at all. It would help to get some clarity on what the intended behavior here is before deciding if anything should be changed / enhanced.

(4) Even with `:disableSuggestions t`, I still get suggestions in the `tide-project-errors` buffer UNTIL I open the referenced file for the suggestion. At that point, the suggestion disappears from the `tide-project-errors` buffer when I rerun the command (UNTIL I restart `tsserver`, at which point all of the suggestions become visible again). There is still some ambiguity here as to if this bug is with Tide or `tsserver`; however, given that opening the file makes the error disappear, I am suspicious that Tide is not sending enough info to `tsserver`. That being said, I know very little of the `tsserver` api and am brand new to emacs/elisp, so I think some direction from a contributor/maintainer on this issue would be ideal; it could certainly be a `tsserver` issue, but I am unsure what the exact issue would be.

**Comment by gdanov** [comment]
> To clarify on the behavior you're seeing, are you saying that for a javascript project you get implicit any errors without having a tsconfig.json?

correct

> (3) The :disableSuggestions t option seems to only affect the tide-project-errors output and not flycheck as a I still get underlining in the code files.

I experience the same

> (4) Even with :disableSuggestions t, I still get suggestions in the tide-project-errors buffer UNTIL I open the referenced file for the suggestion. At that point, the suggestion disappears from the tide-project-errors buffer when I rerun the command ...

oh, I did not notice this was happening until I read this. Yes, I see that too.

flycheck-list-errors provides better summary IMO, where the source and the severity are visible, my problem is I can't figure out how to tell flycheck to ignore info level 

<img width="1438" alt="Screenshot 2019-05-05 at 16 31 37" src="https://user-images.githubusercontent.com/957113/57195485-8bcdcd80-6f53-11e9-877c-ca05c1bda0bd.png">

**Comment by jclangst** [comment]
@gdanov Glad to see that I am not crazy with this not working out of the box.

The flycheck interface for errors is great and is exactly what I was expecting the interface for tide to look like. You can use the default `"f"` keybinding to filter the errors to ignore "info". Unfortunately, flycheck only works for opened buffers and has no way to get all project errors without opening all the files. Ideally, I'd have a simple keybinding to show all of the project errors as changes in one file can have cascading errors elsewhere without flagging any errors in the file itself.

I am not sure why you'd be getting inferredProject with a valid tsconfig.json though.

**Comment by ananthakumaran** [comment]
`:disableSuggestions t` might not work as tide specifically asks the server for suggestions in flycheck callback. In tide-project-errors likely the summary will never be shown. Both of these needs to be handled at tide level, there should be a custom config to toggle this feature.

> The left one is from the original repo from which I raised this bug; note that there is no summary stats at the bottom

This looks like a bug. Tide waits for the results of all files in the project before showing the summary stats. Tsserver will either respond with a list of errors or an empty list in case of no errors for each file. Sometimes tide might be waiting for response that might never come (like if disableSuggestions is set to true, and tide might be waiting for suggestion results). If there is a reliable way to reproduce this bug, it would be useful.

**Comment by jclangst** [comment]
@ananthakumaran Thanks for the response. For the summary stat bug, you should be able to reproduce using either of the situations mentioned on (1) from [this comment](https://github.com/ananthakumaran/tide/issues/312#issuecomment-489413456). You can use my example repo from above to replicate the issue.

> In tide-project-errors likely the summary will never be shown. Both of these needs to be handled at tide level, there should be a custom config to toggle this feature.

I am a little confused by the statement "the summary will never be shown." Are you referring to the summary stats or some other summary? If the summary stats, wouldn't fixing the bug mentioned later in your comment fix this?

> tide specifically asks the server for suggestions in flycheck callback

Are you saying that for `tide-project-errors` it actually uses flycheck's callback functionality? When I was looking at the code it at first appeared that it was using the `projectInfo` request to `tsserver` but maybe I missed something.

That all being said, my biggest show stopping issue is (4) from [this comment](https://github.com/ananthakumaran/tide/issues/312#issuecomment-489413456). To me it doesn't make sense for the `tide-project-errors` buffer to change just based on which other buffers I have open. I am hoping that we can fix it so that if I have `:disableSuggestions t`, then it immediately disregards suggestions and doesn't wait until I open the corresponding file buffer to remove them from the error list.

**Comment by ananthakumaran** [comment]
I opened a PR https://github.com/ananthakumaran/tide/pull/313 which introduces a toggle. I haven't got time to test it well. It should fix the suggestion problem in both flycheck error list and tide-project-errors

**Comment by ananthakumaran** [comment]
> If the summary stats, wouldn't fixing the bug mentioned later in your comment fix this?

if the issue was caused by `disableSuggestions t`, then yes the above PR should fix it. In case it's a different issue, then I would need a way to reproduce the issue. Please test the PR and let me know if the issue is not fixed.

**Comment by jclangst** [comment]
@ananthakumaran Thank you for the PR. I am happy to test it.

Just for my own edification, I want to be clear on how the data for `tide-project-errors` is being generated. Based on our comments and just looking at the diff from your PR, it appears that tide aggregates the results from applying flycheck to all of the project files. Is that correct?

**Comment by jclangst** [comment]
I have tested the PR by including the PR branch and adding `(setq tide-disable-suggestions t)` to my setup. With this option enabled, the flycheck suggestion underlines are no longer appearing in the file buffers. However, I still have the suggestions in the `tide-project-errors` dialogue. Ideally, we could get the opposite with the flycheck suggestions still showing and the `tide-project-errors` suggestions not showing. Additionally, the `tide-project-errors` buffer is not showing summary stats.

**Comment by jclangst** [comment]
Submitted a PR #315 to your PR that fixes the bugs I found.

**Comment by gdanov** [comment]
after some experimenting I see the behavior is rooted in tsserver. I reproduce it with VScode 1:1

**Comment by jclangst** [comment]
Interesting. That is good to know. I'll open an issue with them and link it here.

**Comment by ananthakumaran** [comment]
Closing this with the assumption that all the issue raised in this thread has been fixed in master. If anything is still not solved, feel free to open new issue.

**Comment by gdanov** [comment]
> Interesting. That is good to know. I'll open an issue with them and link it here.

there are some hints here https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files

the way it looks to me is: there are some defaults in the tsserver behavior that are not intuitive to noobs like me coming from JS and used to fine-tune the feedback from the linter. Would be nice if the Tide readme/wiki put a warning or note regarding this so ppl avoid wasting time. I'd gladly do it but I don't feel like I understand what's going on and what's the intent of the tsserver
